//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PolaganjeIspita.Client.Models.EFRepository
{
    using System;
    using System.Collections.Generic;
    
    public partial class PredmetModel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PredmetModel()
        {
            this.Prijava = new HashSet<PrijavaModel>();
        }
    
        public int PredmetID { get; set; }
        public string Naziv { get; set; }
        public string Profesor { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PrijavaModel> Prijava { get; set; }
    }
}
