//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PolaganjeIspita.Client.Models.EFRepository
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrijavaModel
    {
        public int PredmetID { get; set; }
        public int StudentID { get; set; }
        public int Ocena { get; set; }
    
        public virtual PredmetModel Predmet { get; set; }
        public virtual StudentModel Student { get; set; }
    }
}
