//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PolaganjeIspita.Client.Models.EFRepository
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentModel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StudentModel()
        {
            this.Prijava = new HashSet<PrijavaModel>();
        }
    
        public int StudentID { get; set; }
        public string Ime { get; set; }
        public string Prezime { get; set; }
        public short GodinaUpisa { get; set; }
        public string DatumRodjenja { get; set; }
        public float Skolarina { get; set; }
        public Nullable<float> Prosek { get; set; }
        public int SmerID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PrijavaModel> Prijava { get; set; }
        public virtual SmerModel Smer { get; set; }
    }
}
